# Generated by Django 5.2 on 2025-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('credit_limit', models.FloatField(default=0.0, null=True)),
                ('account_balance', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
